version: "2"
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/srv/nginx/etc/conf.d:/etc/nginx/conf.d"
            - "/srv/nginx/etc/includes:/etc/nginx/includes"
            - "/srv/nginx/www:/var/www"
            - "/srv/letsencrypt:/etc/letsencrypt"
        depends_on:
            - "gogs"
            - "artifactory"
    gogs:
        image: gogs/gogs
        ports:
            - "22:22"
        volumes:
            - "/srv/gogs/data:/data"
    artifactory:
        image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss
        volumes:
            - "/srv/artifactory/etc:/var/opt/jfrog/artifactory/etc"
            - "/srv/artifactory/data:/var/opt/jfrog/artifactory/data"
